

export const CLOSE_POP_UP = "CLOSE_POP_UP"

export const  USER_POP_OPEN = "USER_POP_OPEN"



export const CATEGORY_POP_CREATE = "CATEGORY_POP_CREATE"
export const CATEGORY_POP_UPDATE = "CATEGORY_POP_UPDATE"




export const POSTS_POP_CREATE = "POSTS_POP_CREATE"
export const POSTS_POP_UPDATE = "POSTS_POP_UPDATE"
export const POSTS_POP_GALLERY = "POSTS_POP_GALLERY"
export const POSTS_POP_PROPERTIES = "POSTS_POP_PROPERTIES"
export const POSTS_POP_COLORS = "POSTS_POP_COLORS"



export const COMMENTS_POP_REPLYS = "COMMENTS_POP_REPLYS"
